{% set data = load_setup_py_data() %}

package:
  name: pyoviz
  version: {{ data['version'] }}

source:
  git_url: https://github.com/pyomeca/pyoviz

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pyyaml
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - pyoviz

about:
  home: https://github.com/pyomeca/pyoviz
  summary: Pyomeca visualization toolkit

extra:
    recipe-maintainers:
        - mrtnz

